MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "./pretrained/swin_base_patch4_window12_384_22k.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

  AUDIO:
    FREEZE_AUDIO_EXTRACTOR: True 
    PRETRAINED_VGGISH_MODEL_PATH: "./pretrained/vggish-10086976.pth"
    PREPROCESS_AUDIO_TO_LOG_MEL: False
    POSTPROCESS_LOG_MEL_WITH_PCA: False
    PRETRAINED_PCA_PARAMS_PATH: "./pretrained/vggish_pca_params-970ea276.pth"

DATASETS:
  TRAIN: ("avss4_sem_seg_train",)
  TEST: ("avss4_sem_seg_val",)
SOLVER:
  IMS_PER_BATCH: 2 # 8
  BASE_LR: 0.0001
  MAX_ITER: 45000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS: 
    ENABLED: True  
    CLIP_TYPE: "full_model"   
    CLIP_VALUE: 0.01   
    NORM_TYPE: 2.0
  AMP:
    ENABLED: False
INPUT:
  AUGMENTATION: True  
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 384) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 384
  MAX_SIZE_TRAIN: 896 
  MAX_SIZE_TEST: 896 
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (384, 384)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 384 
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "avss4_semantic"
TEST:
  EVAL_PERIOD: 1000
  AUG:  
    ENABLED: False
    MIN_SIZES: [128, 224, 384]
    MAX_SIZE: 1536
    FLIP: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
VERSION: 2